### ISSUE TITLE
How to create appxpackage

### ISSUE THREAD

**Issue by NGame1** [wherewhere/CoreAppUWP#1]
Hi there, 
Did you try to create Appx, AppxPackage, MSix, or, MSixPackage?
And also, I wonder how to add a simple Blank page for example.

**Comment by wherewhere** [comment]
Sorry, I don't know. 🤣

**Comment by NGame1** [comment]
Hm, Nice. 
I don't know exactly how to use MakeAppx.exe I think it should be the right way to create package (if it works!) 
I tried to add an installer project to the solution and use that to create package but it didn't work.

**Comment by wherewhere** [comment]
```
MakeAppx pack /f mapping_filepath /p filepath.appx
```
You can find command at https://learn.microsoft.com/en-us/windows/win32/appxpkg/make-appx-package--makeappx-exe-

**Comment by NGame1** [comment]
I know that, but I don't know what is the mapping file.
Maybe I should search more about it. 
However, seems this repo will not be so much helpful as adding pages and etc, will not be easy.

**Comment by wherewhere** [comment]
Package the folder which has `AppxManifest.xml`

**Comment by wherewhere** [comment]
It can package now.
